default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  port: 5432
  username: postgres
  password: iam3489495

development:
  <<: *default
  database: language_app_development

test:
  <<: *default
  database: language_app_test

production:
  <<: *default
  database: language_app_production
